// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;

namespace Ssalddel.Simulation.Contracts
{
    /// <summary>
    /// 안정 WI 고유 식별자에 한국어 기능명·단일 책임·음양 정의를 연결한다.
    /// 원본은 세계 상호작용·단일 책임·조립 흐름·사분면 대장이며 이 파일은 직접 수정하지 않는다.
    /// </summary>
    public sealed class Simulation세계상호작용이름Definition
    {
        public Simulation세계상호작용이름Definition(
            string worldInteractionId, string groupCode,
            string 한국어작업군명, int 대장순번, string 한국어기능명,
            string 책임종류코드, string 주요결과코드, string 단일책임판정코드,
            string 음양분류Code, string 음양판정방식Code, bool actor전환필요)
        {
            WorldInteractionId = worldInteractionId;
            GroupCode = groupCode;
            this.한국어작업군명 = 한국어작업군명;
            this.대장순번 = 대장순번;
            this.한국어기능명 = 한국어기능명;
            this.책임종류코드 = 책임종류코드;
            this.주요결과코드 = 주요결과코드;
            this.단일책임판정코드 = 단일책임판정코드;
            this.음양분류Code = 음양분류Code;
            this.음양판정방식Code = 음양판정방식Code;
            this.Actor전환필요 = actor전환필요;
        }

        public string WorldInteractionId { get; }
        public string GroupCode { get; }
        public string 한국어작업군명 { get; }
        public int 대장순번 { get; }
        public string 한국어기능명 { get; }
        public string 책임종류코드 { get; }
        public string 주요결과코드 { get; }
        public string 단일책임판정코드 { get; }
        public string 음양분류Code { get; }
        public string 음양판정방식Code { get; }
        public bool Actor전환필요 { get; }
        public string 한국어표시명 => 한국어작업군명
            + " · " + 한국어기능명 + " (" + WorldInteractionId + ")";
    }

    public static class Simulation세계상호작용이름Catalog
    {
        private static readonly Simulation세계상호작용이름Definition[] 항목들 =
        {
            new Simulation세계상호작용이름Definition("WI-ACTOR-01", "ACTOR", "행위자 공통 물품·장착", 1, "물품 획득", "ActorIntent", "ItemAcquired", "Atomic", "Yang", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-ACTOR-02", "ACTOR", "행위자 공통 물품·장착", 2, "장착 상태 변경", "ActorIntent", "ItemEquipmentChanged", "Atomic", "Yin", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-ACTOR-03", "ACTOR", "행위자 공통 물품·장착", 3, "지식 습득", "ActorIntent", "RecipeKnowledgeAdded", "Atomic", "Yin", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-ACTOR-CONSUME", "ACTOR", "행위자 공통 물품·장착", 4, "물품 섭취", "ActorIntent", "ItemConsumed", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-ACTOR-PLAN-SET", "ACTOR", "행위자 공통 물품·장착", 5, "개인 계획 설정", "ActorIntent", "PersonalPlanSet", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-CARD-01", "CARD", "카드 맥락", 1, "현재 세계의 메이저 아르카나 활성화", "ActorIntent", "MajorArcanaActivated", "AtomicBundle", "Yin", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-CITY-01", "CITY", "도심 운영", 1, "도심 서비스 수요 확정", "ActorIntent", "CityDemandConfirmed", "Atomic", "Yin", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-CITY-02", "CITY", "도심 운영", 2, "도심 서비스용 지역 재고 배정", "AuthorityTransition", "CityInventoryAllocated", "AlternativeOutcomes", "NotApplicable", "NotApplicable", false),
            new Simulation세계상호작용이름Definition("WI-CITY-03", "CITY", "도심 운영", 3, "도심 주민 서비스 처리", "ActorIntent", "CityServiceCompleted", "AlternativeOutcomes", "Yin", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-CITY-04", "CITY", "도심 운영", 4, "도심 서비스 결과 확인", "ActorIntent", "CityServiceChoiceAvailable", "Atomic", "Yin", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-CITY-RESTAURANT-ACCEPT", "CITY", "도심 운영", 5, "음식점 NPC 주문 자동 수락", "ActorIntent", "RestaurantResponseRecorded", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-CITY-RESTAURANT-COOK", "CITY", "도심 운영", 6, "음식점 조리 자리 배정", "ActorIntent", "RestaurantCookingScheduled", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-CITY-SYNTHETIC-ASSIGN", "CITY", "도심 운영", 7, "기사 배정", "ActorIntent", "Assigned", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-CITY-SYNTHETIC-MOVE", "CITY", "도심 운영", 8, "도로·출입구 이동", "ActorIntent", "PositionAdvanced", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-CITY-SYNTHETIC-PICKUP", "CITY", "도심 운영", 9, "음식 픽업", "ActorIntent", "PickedUp", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-CITY-SYNTHETIC-DELIVER", "CITY", "도심 운영", 10, "주택 전달", "ActorIntent", "Delivered", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-CITY-SYNTHETIC-RECEIVE", "CITY", "도심 운영", 11, "주문자 수령", "ActorIntent", "Received", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-CITY-SYNTHETIC-RETURN", "CITY", "도심 운영", 12, "기사 복귀", "ActorIntent", "Returned", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-CITY-SYNTHETIC-MART-RESERVE", "CITY", "도심 운영", 13, "마트 예약", "ActorIntent", "Reserved", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-CITY-SYNTHETIC-MART-PICK", "CITY", "도심 운영", 14, "마트 피킹", "ActorIntent", "Picked", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-CITY-SYNTHETIC-MART-PACK", "CITY", "도심 운영", 15, "마트 포장", "ActorIntent", "Packed", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-CITY-SYNTHETIC-MART-STAGE", "CITY", "도심 운영", 16, "마트 인계대 적치", "ActorIntent", "ReadyForCourier", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-CITY-SYNTHETIC-LIFE-SHIFT", "CITY", "도심 운영", 17, "근무 복귀", "ActorIntent", "Working", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-CITY-SYNTHETIC-LIFE-REST", "CITY", "도심 운영", 18, "인계 후 휴식", "ActorIntent", "Resting", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-CITY-SYNTHETIC-DEPOT-INSPECT", "CITY", "도심 운영", 19, "보충창고 입고 검수", "ActorIntent", "Inspected", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-CITY-SYNTHETIC-DEPOT-PUTAWAY", "CITY", "도심 운영", 20, "검수 물품 적치", "ActorIntent", "Stored", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-CITY-SYNTHETIC-DEPOT-RESERVE", "CITY", "도심 운영", 21, "보충 출고 예약", "ActorIntent", "Reserved", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-CITY-SYNTHETIC-DEPOT-PICK", "CITY", "도심 운영", 22, "보충 물품 피킹", "ActorIntent", "Picked", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-CITY-SYNTHETIC-DEPOT-PACK", "CITY", "도심 운영", 23, "보충 물품 포장", "ActorIntent", "Packed", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-CITY-SYNTHETIC-DEPOT-STAGE", "CITY", "도심 운영", 24, "보충 물품 상차대 인계", "ActorIntent", "Ready", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-CITY-SYNTHETIC-FREIGHT-LOAD", "CITY", "도심 운영", 25, "화물차 상차", "ActorIntent", "Loaded", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-CITY-SYNTHETIC-FREIGHT-UNLOAD", "CITY", "도심 운영", 26, "마트 화물 하차", "ActorIntent", "Unloaded", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-CITY-SYNTHETIC-MART-INBOUND", "CITY", "도심 운영", 27, "마트 검수 입고", "ActorIntent", "Received", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-COMMUNITY-VISITOR-STAY", "COMMUNITY", "공동체 방문·관계", 1, "방문자 임시 체류 결정", "ActorIntent", "CommunityVisitorStayDecisionRecorded", "AtomicBundle", "Yin", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-COMMUNITY-COOPERATION-PROPOSE", "COMMUNITY", "공동체 방문·관계", 2, "공동체 협력 제안", "ActorIntent", "CooperationProposed", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-COMMUNITY-ENTRANCE-POLICY-SET", "COMMUNITY", "공동체 방문·관계", 3, "공동체 출입 정책 설정", "ActorIntent", "EntrancePolicySet", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-COMMUNITY-HIRE", "COMMUNITY", "공동체 방문·관계", 4, "NPC 고용 확정", "ActorIntent", "NpcEmploymentConfirmed", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-COMMUNITY-MEMBERSHIP-CONFIRM", "COMMUNITY", "공동체 방문·관계", 5, "공동체 정식 편입 확정", "ActorIntent", "CommunityMembershipConfirmed", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-COMMUNITY-REMOTE-RESPONSE", "COMMUNITY", "공동체 방문·관계", 6, "원격 응대 지시 확정", "ActorIntent", "RemoteResponseOrderConfirmed", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-COMMUNITY-SUPPORT-MISSION-JOIN", "COMMUNITY", "공동체 방문·관계", 7, "공동 지원 임무 참여", "ActorIntent", "SupportMissionParticipationConfirmed", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-GUEST-PERMISSION-SET", "COMMUNITY", "공동체 방문·관계", 8, "손님 활동 권한 설정", "ActorIntent", "GuestPermissionSet", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-CON-01", "CON", "영역 건설", 1, "영역 건물 건설 확정", "ActorIntent", "AreaBuildingOperational", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-CON-BLUEPRINT-PLACE", "CON", "영역 건설", 2, "건설 청사진 배치", "ActorIntent", "ConstructionBlueprintPlaced", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-CON-DEMOLISH", "CON", "영역 건설", 3, "건설물 해체", "ActorIntent", "ConstructionDemolished", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-CON-MATERIAL-DEPOSIT", "CON", "영역 건설", 4, "건설 재료 투입", "ActorIntent", "ConstructionMaterialDeposited", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-CON-WORK-CONTRIBUTE", "CON", "영역 건설", 5, "건설 시공 기여", "ActorIntent", "ConstructionWorkContributed", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-FARM-01", "FARM", "농장 생산", 1, "경작지 밭갈이", "ActorIntent", "SoilTilled", "Atomic", "Yang", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-FARM-02", "FARM", "농장 생산", 2, "경작지 씨앗 파종", "ActorIntent", "CultivationStarted", "Atomic", "Yang", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-FARM-03", "FARM", "농장 생산", 3, "농작물 생육 관리", "ActorIntent", "CropCareApplied", "Atomic", "Yang", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-FARM-04", "FARM", "농장 생산", 4, "익은 농작물 수확", "ActorIntent", "HarvestLotCreated", "AtomicBundle", "Yang", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-FARM-05", "FARM", "농장 생산", 5, "수확물 집하장 모으기", "ActorIntent", "HarvestLotCollected", "Atomic", "Yang", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-FARM-06", "FARM", "농장 생산", 6, "출하 물량 포장", "ActorIntent", "PackageLotCreated", "AtomicBundle", "Yang", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-FARM-DEFENSE-MOBILIZE", "FARM", "농장 생산", 7, "방위 분대 소집", "ActorIntent", "FarmDefenseSquadMobilized", "AtomicBundle", "NotApplicable", "NotApplicable", false),
            new Simulation세계상호작용이름Definition("WI-SQUAD-ASSIGN", "FARM", "농장 생산", 8, "경비 초소 분대 배정", "ActorIntent", "FarmDefenseSquadAssigned", "Atomic", "Yin", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-SQUAD-SUPPLY", "FARM", "농장 생산", 9, "경비 분대 식량·장비 보급", "ActorIntent", "FarmDefenseSquadSupplied", "Atomic", "Yin", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-FARM-DEFENSE-RESOLVE", "FARM", "농장 생산", 10, "Farm 방어 성공 결과 발현", "ActorIntent", "FarmDefenseResolved", "AtomicBundle", "NotApplicable", "NotApplicable", false),
            new Simulation세계상호작용이름Definition("WI-FARM-DEFENSE-RETURN", "FARM", "농장 생산", 11, "Farm 방위 분대 초소 귀환 인계", "ActorIntent", "FarmDefenseSquadReturned", "Atomic", "NotApplicable", "NotApplicable", false),
            new Simulation세계상호작용이름Definition("WI-FARM-FIELD-BOUNDARY-CONFIRM", "FARM", "농장 생산", 12, "밭 경계 확정", "ActorIntent", "FieldBoundaryConfirmed", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-FARM-SOIL-AMEND", "FARM", "농장 생산", 13, "토양 개량", "ActorIntent", "SoilAmended", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-FARM-WATER-TRANSFER", "FARM", "농장 생산", 14, "농업 용수 이송", "ActorIntent", "IrrigationWaterTransferred", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-001", "HUB", "물류 거점 창고", 1, "입고 화물 검수", "ActorIntent", "StorageEligible", "LegacyCompositeMigrationRequired", "Yin", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-002", "HUB", "물류 거점 창고", 2, "검수 완료 화물 창고 적재", "ActorIntent", "PutAwayCompleted", "AtomicBundle", "Yang", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-HUB-03", "HUB", "물류 거점 창고", 3, "출고 대상 재고 요청", "ActorIntent", "OutboundRequested", "Atomic", "Yin", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-HUB-04", "HUB", "물류 거점 창고", 4, "출고 대상 재고 피킹", "AuthorityTransition", "StockPicked", "ActorResponsibilityMigrationRequired", "Yang", "Fixed", true),
            new Simulation세계상호작용이름Definition("WI-HUB-05", "HUB", "물류 거점 창고", 5, "피킹 화물 포장", "AuthorityTransition", "OutboundCargoPrepared", "ActorResponsibilityMigrationRequired", "Yang", "Fixed", true),
            new Simulation세계상호작용이름Definition("WI-HUB-06", "HUB", "물류 거점 창고", 6, "출고 차량 상차", "ActorIntent", "HubCargoLoaded", "Atomic", "Yang", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-HUB-DEMAND-ALLOCATE", "HUB", "물류 거점 창고", 7, "Hub 수요 재고 할당", "ActorIntent", "HubDemandInventoryAllocated", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-HUB-SUPPLY-TASK-ACCEPT", "HUB", "물류 거점 창고", 8, "Hub 조달 과제 수락", "ActorIntent", "HubSupplyTaskAccepted", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-LOG-01", "LOG", "영역 간 화물 이동", 1, "출하 차량 상차 확정", "ActorIntent", "CargoTransportReserved", "Atomic", "Yang", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-LOG-02", "LOG", "영역 간 화물 이동", 2, "농장에서 출발", "AuthorityTransition", "CargoDeparted", "ProceduralStepMigrationRequired", "NotApplicable", "NotApplicable", false),
            new Simulation세계상호작용이름Definition("WI-LOG-03", "LOG", "영역 간 화물 이동", 3, "농장에서 물류 거점으로 화물 이동", "AuthorityTransition", "CargoRouteProgressed", "ProceduralStepMigrationRequired", "NotApplicable", "NotApplicable", false),
            new Simulation세계상호작용이름Definition("WI-LOG-04", "LOG", "영역 간 화물 이동", 4, "물류 거점 도착 화물 하차", "AuthorityTransition", "CargoUnloaded", "ProceduralStepMigrationRequired", "NotApplicable", "NotApplicable", false),
            new Simulation세계상호작용이름Definition("WI-LOG-05", "LOG", "영역 간 화물 이동", 5, "물류 거점 도착 화물 인수", "AuthorityTransition", "FreightReceived", "ProceduralStepMigrationRequired", "NotApplicable", "NotApplicable", false),
            new Simulation세계상호작용이름Definition("WI-MARKET-01", "MARKET", "마트 입고·진열", 1, "물류 거점에서 마트로 운송", "ActorIntent", "MarketCargoArrived", "Atomic", "Yang", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-MARKET-02", "MARKET", "마트 입고·진열", 2, "마트 도착 화물 인수", "ActorIntent", "MarketFreightReceived", "Atomic", "Yin", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-MARKET-03", "MARKET", "마트 입고·진열", 3, "마트 입고 상품 검수", "ActorIntent", "MarketStorageEligible", "Atomic", "Yin", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-MARKET-04", "MARKET", "마트 입고·진열", 4, "검수 상품 후방 창고 적재", "ActorIntent", "MarketBackroomStored", "Atomic", "Yang", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-MARKET-05", "MARKET", "마트 입고·진열", 5, "매장 진열대 상품 보충", "ActorIntent", "DisplayStockReplenished", "Atomic", "Yang", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-TOWN-DELIVERY-INSPECT", "MARKET", "마트 입고·진열", 6, "Town 납품 검수", "ActorIntent", "TownDeliveryInspected", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-TOWN-DELIVERY-RECEIVE", "MARKET", "마트 입고·진열", 7, "Town 납품 인수", "ActorIntent", "TownDeliveryReceived", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-TOWN-STOCK-PUTAWAY", "MARKET", "마트 입고·진열", 8, "Town 후방 재고 적재", "ActorIntent", "TownStockPutAway", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-TOWN-STOCK-REPLENISH", "MARKET", "마트 입고·진열", 9, "Town 재고 보충 주문", "ActorIntent", "TownReplenishmentOrderConfirmed", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-TOWN-SUPPLY-DISPATCH", "MARKET", "마트 입고·진열", 10, "Town 공급 운송 출발 확정", "ActorIntent", "TownSupplyDispatched", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-NATURE-01", "NATURE", "자연 탐사·생활 거점", 1, "자연 지역 위험 징후 확인", "ActorIntent", "NatureThreatObserved", "Atomic", "Yang", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-NATURE-02", "NATURE", "자연 탐사·생활 거점", 2, "안전 거점으로 긴급 후퇴", "ActorIntent", "PartyRetreatedToSafeCore", "Atomic", "Yang", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-NATURE-03", "NATURE", "자연 탐사·생활 거점", 3, "훼손된 자연 경로 복원", "ActorIntent", "NatureRouteRestored", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-NATURE-04", "NATURE", "자연 탐사·생활 거점", 4, "탐사대 안전 회복", "ActorIntent", "PartyRecovered", "Atomic", "Yin", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-NATURE-05", "NATURE", "자연 탐사·생활 거점", 5, "벌목 도끼 획득", "ActorIntent", "AxeAcquired", "Atomic", "Yang", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-NATURE-06", "NATURE", "자연 탐사·생활 거점", 6, "나무 벌목 작업 시작", "ActorIntent", "TreeFelled", "AtomicBundle", "Yang", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-NATURE-07", "NATURE", "자연 탐사·생활 거점", 7, "오두막을 지을 터 선정", "ActorIntent", "CabinBlueprintPlaced", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-NATURE-08", "NATURE", "자연 탐사·생활 거점", 8, "오두막 건설 작업 시작", "ActorIntent", "CabinOperational", "AtomicBundle", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-NATURE-09", "NATURE", "자연 탐사·생활 거점", 9, "오두막 안으로 들어가기", "ActorIntent", "PlayerEnteredCabin", "Atomic", "Yang", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-NATURE-10", "NATURE", "자연 탐사·생활 거점", 10, "오두막 밖으로 나가기", "ActorIntent", "PlayerLeftCabin", "Atomic", "Yang", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-NATURE-11", "NATURE", "자연 탐사·생활 거점", 11, "황혼 위협 대응 방식 확정", "ActorIntent", "EncounterResolved", "LegacyCompositeMigrationRequired", "Yang", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-NATURE-12", "NATURE", "자연 탐사·생활 거점", 12, "진행 중 작업 취소", "ActorIntent", "WorkCancelled", "AtomicBundle", "Yin", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-NATURE-13", "NATURE", "자연 탐사·생활 거점", 13, "획득 자원 거점 보관", "ActorIntent", "TimberStored", "AtomicBundle", "Yin", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-NATURE-14", "NATURE", "자연 탐사·생활 거점", 14, "오두막에서 수면·새벽 맞기", "ActorIntent", "DawnReached", "LegacyCompositeMigrationRequired", "Yin", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-NATURE-15", "NATURE", "자연 탐사·생활 거점", 15, "다음 날 거점 확장 계획 선택", "ActorIntent", "ExpansionPlanSelected", "AtomicBundle", "Yin", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-NATURE-16", "NATURE", "자연 탐사·생활 거점", 16, "현장 보급 꾸러미 제작", "ActorIntent", "NatureFieldSupplyPackAdded", "LegacyCompositeMigrationRequired", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-NATURE-17", "NATURE", "자연 탐사·생활 거점", 17, "현장 보급 제작 업무 위임", "ActorIntent", "NpcFieldSupplyPolicySelected", "LegacyCompositeMigrationRequired", "Yin", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-NATURE-18", "NATURE", "자연 탐사·생활 거점", 18, "벌목 통나무 줍기", "ActorIntent", "TimberCollected", "AtomicBundle", "Yang", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-CRAFT-BREW", "NATURE", "자연 탐사·생활 거점", 19, "배합물 달이기", "ActorIntent", "BrewBatchCompleted", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-HEAT-SOURCE-STATE-CHANGE", "NATURE", "자연 탐사·생활 거점", 20, "열원 상태 변경", "ActorIntent", "HeatSourceStateChanged", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-NATURE-HERB-GATHER", "NATURE", "자연 탐사·생활 거점", 21, "약초 채집", "ActorIntent", "HerbGathered", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-NATURE-TRACE-INVESTIGATE", "NATURE", "자연 탐사·생활 거점", 22, "자연 흔적 조사", "ActorIntent", "NatureTraceInvestigated", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-NATURE-19", "NATURE", "자연 탐사·생활 거점", 23, "한스 농장 부러진 손도끼 줍기", "ActorIntent", "HansBrokenAxeCarried", "Atomic", "Yang", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-NATURE-20", "NATURE", "자연 탐사·생활 거점", 24, "한스 농장 울타리 일괄 수리", "ActorIntent", "HansFarmFenceRepaired", "AtomicBundle", "Yin", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-NATURE-HANS-BOUNDARY-PATROL", "NATURE", "자연 탐사·생활 거점", 25, "한스와 농장 경계 순찰", "ActorIntent", "FarmBoundaryPatrolCompleted", "AtomicBundle", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-ORDER-01", "ORDER", "주민 주문·소비", 1, "주민 주문 확정", "ActorIntent", "OrderConfirmed", "Atomic", "Yin", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-ORDER-02", "ORDER", "주민 주문·소비", 2, "주문 상품 재고 예약", "AuthorityTransition", "OrderStockReserved", "ProceduralStepMigrationRequired", "NotApplicable", "NotApplicable", false),
            new Simulation세계상호작용이름Definition("WI-ORDER-03", "ORDER", "주민 주문·소비", 3, "주문 상품 피킹", "AuthorityTransition", "OrderStockPicked", "ActorResponsibilityMigrationRequired", "Yang", "Fixed", true),
            new Simulation세계상호작용이름Definition("WI-ORDER-04", "ORDER", "주민 주문·소비", 4, "주문 상품 포장", "AuthorityTransition", "OrderPacked", "ActorResponsibilityMigrationRequired", "Yang", "Fixed", true),
            new Simulation세계상호작용이름Definition("WI-ORDER-05", "ORDER", "주민 주문·소비", 5, "주문 상품 수령 준비", "AuthorityTransition", "OrderReadyForPickup", "ProceduralStepMigrationRequired", "NotApplicable", "NotApplicable", false),
            new Simulation세계상호작용이름Definition("WI-ORDER-06", "ORDER", "주민 주문·소비", 6, "주민 주문 상품 수령", "ActorIntent", "OrderFulfilled", "Atomic", "Yang", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-ORDER-07", "ORDER", "주민 주문·소비", 7, "주민 상품 소비", "ActorIntent", "ResidentConsumed", "Atomic", "Yin", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-REFLECT-01", "REFLECT", "거점 성찰", 1, "승인 자료로 거점 성찰 확정", "ActorIntent", "InnerLearningPending", "Atomic", "Yin", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-REFLECT-HANS-FARM-CRISIS-DEBRIEF", "REFLECT", "거점 성찰", 2, "한스 농장 위기 사후 성찰", "ActorIntent", "HansFarmCrisisDebriefCompleted", "AtomicBundle", "Yin", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-REVIEW-01", "REVIEW", "업무 검토", 1, "NPC 업무 결과 검토 확정", "ActorIntent", "NpcWorkReviewConfirmed", "AtomicBundle", "Yin", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-WORLD-01", "WORLD", "공통 세계 운영", 1, "NPC에게 반복 업무 배정", "SharedDecisionRule", "NpcAssigned", "Atomic", "NotApplicable", "NotApplicable", false),
            new Simulation세계상호작용이름Definition("WI-WORLD-02", "WORLD", "공통 세계 운영", 2, "NPC에게 업무 역량 위임", "ActorIntent", "NpcCapabilityGranted", "Atomic", "Yin", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-WORLD-03", "WORLD", "공통 세계 운영", 3, "진행 중 세계 업무 취소", "ActorIntent", "TaskCancelled", "AtomicBundle", "Yin", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-WORLD-04", "WORLD", "공통 세계 운영", 4, "손상된 시설 수리", "ActorIntent", "FacilityRepaired", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-WORLD-05", "WORLD", "공통 세계 운영", 5, "새로운 지역 발견", "ActorIntent", "RegionDiscovered", "Atomic", "Yang", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-WORLD-06", "WORLD", "공통 세계 운영", 6, "일행 역할 카드 장착", "ActorIntent", "TeamRoleCardEquipped", "Atomic", "Yin", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-WORLD-07", "WORLD", "공통 세계 운영", 7, "세계 활동 상태 변경", "ActorIntent", "TeamActivityStarted", "LegacyCompositeMigrationRequired", "Yin", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-WORLD-08", "WORLD", "공통 세계 운영", 8, "하루 운영 턴 마감", "ActorIntent", "TurnClosed", "Atomic", "Yin", "Fixed", false),
            new Simulation세계상호작용이름Definition("WI-COMBAT-DIRECT-CONTROL-SET", "WORLD", "공통 세계 운영", 9, "직접 전투 조종 전환", "ActorIntent", "ActorDirectControlChanged", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-COMBAT-TACTICAL-COMMAND", "WORLD", "공통 세계 운영", 10, "분대 전술 명령 확정", "ActorIntent", "SquadTacticalOrderConfirmed", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-EXPEDITION-DISPATCH", "WORLD", "공통 세계 운영", 11, "탐사 임무 파견", "ActorIntent", "ExpeditionDispatched", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-INVENTORY-BELOW-RESERVE-SALE-CONFIRM", "WORLD", "공통 세계 운영", 12, "목표 비축 미달 판매 확정", "ActorIntent", "BelowReserveSaleConfirmed", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-SURVIVAL-RATION-POLICY-SET", "WORLD", "공통 세계 운영", 13, "생존 배급 정책 설정", "ActorIntent", "RationPolicySet", "Atomic", "Contextual", "ExecutionContext", false),
            new Simulation세계상호작용이름Definition("WI-WORLD-RESOURCE-REGENERATE", "WORLD", "공통 세계 운영", 14, "세계 자원 재생", "AuthorityTransition", "ResourceAvailabilityRestored", "AlternativeOutcomes", "NotApplicable", "NotApplicable", false),
            new Simulation세계상호작용이름Definition("WI-WORLD-BOUNDED-MANAGEMENT-GRANT", "WORLD", "공통 세계 운영", 15, "제한된 생활 거점 관리권 부여", "ActorIntent", "BoundedManagementAuthorityGranted", "Atomic", "Yin", "Fixed", false),
        };

        private static readonly Dictionary<string, string> 문맥음양ByKey =
            new Dictionary<string, string>(StringComparer.Ordinal)
            {
                ["playable-loop:nature-building-learning.v1|WI-CON-01"] = "Yin",
                ["playable-loop:nature-field-supply-return.v1|WI-NATURE-16"] = "Yin",
                ["playable-loop:nature-shelter-foundation.v1|WI-NATURE-07"] = "Yin",
                ["playable-loop:nature-shelter-foundation.v1|WI-NATURE-08"] = "Yin",
                ["playable-loop:nature-twilight-return.v1|WI-NATURE-03"] = "Yang",
            };

        public static IReadOnlyList<Simulation세계상호작용이름Definition> All => 항목들;

        public static Simulation세계상호작용이름Definition? Find(string worldInteractionId)
        {
            if (string.IsNullOrWhiteSpace(worldInteractionId)) return null;
            foreach (var 항목 in 항목들)
                if (string.Equals(항목.WorldInteractionId, worldInteractionId,
                        StringComparison.Ordinal))
                    return 항목;
            return null;
        }

        public static string 한국어기능명(string worldInteractionId)
            => Find(worldInteractionId)?.한국어기능명
               ?? (worldInteractionId ?? string.Empty);

        public static string 한국어표시명(string worldInteractionId)
            => Find(worldInteractionId)?.한국어표시명
               ?? (string.IsNullOrWhiteSpace(worldInteractionId)
                   ? "알 수 없는 세계 상호작용"
                   : "알 수 없는 세계 상호작용 (" + worldInteractionId + ")");

        public static string 책임종류코드(string worldInteractionId)
            => Find(worldInteractionId)?.책임종류코드 ?? string.Empty;

        public static string 주요결과코드(string worldInteractionId)
            => Find(worldInteractionId)?.주요결과코드 ?? string.Empty;

        public static string 단일책임판정코드(string worldInteractionId)
            => Find(worldInteractionId)?.단일책임판정코드 ?? string.Empty;

        public static string 음양분류Code(string worldInteractionId)
            => Find(worldInteractionId)?.음양분류Code ?? "Unclassified";

        public static string 음양판정방식Code(string worldInteractionId)
            => Find(worldInteractionId)?.음양판정방식Code ?? string.Empty;

        public static string 문맥음양Code(string worldInteractionId,
            string playableLoopStableId)
        {
            if (string.IsNullOrWhiteSpace(worldInteractionId)
                || string.IsNullOrWhiteSpace(playableLoopStableId))
                return string.Empty;
            return 문맥음양ByKey.TryGetValue(playableLoopStableId.Trim()
                       + "|" + worldInteractionId.Trim(), out var value)
                ? value : string.Empty;
        }
    }
}
