// Generated by eng/world-seedbeds/manage-neighborhood-maps.ps1. Do not edit.
// 기존 합성 XZ 배치 기준. 실제 World 배치 승인이나 운영 상태가 아니다.
using System;
namespace Ssalddel.Simulation.Contracts { public static class 가상동네배치기준 {
public const string Revision = "synthetic-neighborhood.r1";
public static (double x, double z) 기준점(string id) { switch(id) {
case "restaurant-work": return (10d,5d);
case "restaurant-door": return (10d,3.95d);
case "restaurant-bay": return (10d,2.5d);
case "home-a-resident": return (29d,26d);
case "home-a-door": return (30d,23.95d);
case "home-a-receive": return (30d,24d);
case "home-a-bay": return (30d,22.5d);
case "home-b-resident": return (9d,26d);
case "home-b-door": return (10d,23.95d);
case "home-b-receive": return (10d,24d);
case "home-b-bay": return (10d,22.5d);
case "mart-work": return (0d,-14d);
case "mart-turn": return (-10d,-14d);
case "mart-handoff": return (-10d,-8d);
case "mart-bay": return (-10d,-2.5d);
case "mart-inbound": return (-14d,-8d);
case "mart-inbound-bay": return (-14d,-3d);
case "mart-inbound-turn": return (-14d,-14d);
case "mart-shelf-0": return (-8d,-15d);
case "mart-shelf-1": return (-4d,-15d);
case "mart-pack": return (0d,-15d);
case "mart-counter": return (-11d,-8d);
case "mart-server-inbound": return (-9d,-9d);
case "mart-server-inspect": return (-6d,-11d);
case "mart-server-wait": return (0d,-12d);
case "mart-server-shelf-access": return (-8d,-13.5d);
case "depot-work": return (-22d,-14d);
case "depot-inbound": return (-26d,-8d);
case "depot-bay": return (-26d,-3d);
case "depot-turn": return (-26d,-14d);
case "junction--26": return (-26d,0d);
case "junction--14": return (-14d,0d);
case "junction--10": return (-10d,0d);
case "junction-0": return (0d,0d);
case "junction-10": return (10d,0d);
case "junction-20": return (20d,0d);
case "home-junction-10": return (10d,20d);
case "home-junction-20": return (20d,20d);
case "home-junction-30": return (30d,20d);
case "waiting-0": return (-6d,-4d);
case "waiting-1": return (0d,-4d);
case "waiting-2": return (6d,-4d);
case "waiting-3": return (10d,16d);
case "waiting-4": return (30d,16d);
default: throw new ArgumentException("NeighborhoodAnchorMissing", nameof(id)); } }
public static (double x, double z, double width, double depth) 시설(string id) { switch(id) {
case "facility:sim.restaurant-1": return (10d,7d,6d,6d);
case "facility:synthetic:a": return (30d,27d,6d,6d);
case "facility:synthetic:b": return (10d,27d,6d,6d);
case "facility:synthetic:mart": return (-3d,-12d,18d,10d);
case "facility:synthetic:depot": return (-26d,-12d,16d,10d);
case "road:east": return (4d,0d,36d,4d);
case "road:west": return (-25d,0d,22d,4d);
case "road:trunk": return (20d,10d,4d,24d);
case "road:homes": return (20d,20d,24d,4d);
default: throw new ArgumentException("NeighborhoodInstanceMissing", nameof(id)); } }
public static (double x, double z)[] 대기점() => new[] { 기준점("waiting-0"),기준점("waiting-1"),기준점("waiting-2"),기준점("waiting-3"),기준점("waiting-4") };
public static (double x, double z)[] 경로(string id) { switch(id) {
case "main-road": return new[] { 기준점("junction--26"),기준점("junction--14"),기준점("junction--10"),기준점("junction-0"),기준점("junction-10"),기준점("junction-20") };
case "home-road": return new[] { 기준점("home-junction-10"),기준점("home-junction-20"),기준점("home-junction-30") };
case "trunk": return new[] { 기준점("junction-20"),기준점("home-junction-20") };
case "restaurant-exit": return new[] { 기준점("restaurant-work"),기준점("restaurant-bay"),기준점("junction-10") };
case "mart-exit": return new[] { 기준점("mart-work"),기준점("mart-turn"),기준점("mart-handoff"),기준점("mart-bay"),기준점("junction--10") };
case "mart-inbound": return new[] { 기준점("mart-work"),기준점("mart-inbound-turn"),기준점("mart-inbound"),기준점("mart-inbound-bay"),기준점("junction--14") };
case "depot-exit": return new[] { 기준점("depot-work"),기준점("depot-turn"),기준점("depot-inbound"),기준점("depot-bay"),기준점("junction--26") };
case "home-a-access": return new[] { 기준점("home-junction-30"),기준점("home-a-bay"),기준점("home-a-receive") };
case "home-b-access": return new[] { 기준점("home-junction-10"),기준점("home-b-bay"),기준점("home-b-receive") };
case "waiting-0-access": return new[] { 기준점("waiting-0"),기준점("junction-0") };
case "waiting-1-access": return new[] { 기준점("waiting-1"),기준점("junction-0") };
case "waiting-2-access": return new[] { 기준점("waiting-2"),기준점("junction-10") };
case "waiting-3-access": return new[] { 기준점("waiting-3"),기준점("home-junction-10") };
case "waiting-4-access": return new[] { 기준점("waiting-4"),기준점("home-junction-30") };
default: throw new ArgumentException("NeighborhoodPathMissing", nameof(id)); } }
} }
namespace Ssalddel.Simulation.Contracts { public static class 동네좌표참고확장 {
public const string 원본Hash = "13FFD04A946EC7EEC28222C8C3762F2E77AAB919CD250888CDAAF7F51CCE303B";
public static (double x, double z, double size) 구역 => (550d,8d,1000d);
public static (string id, string name, double x, double z)[] 위치() => new (string, string, double, double)[] {
("market-reference:myeonmok","면목시장",363.55d,-120.015d),
("market-reference:myeonmok-alley","면목골목시장",199.341d,-347.862d),
("market-reference:sagajeong","사가정시장",635.556d,50.628d),
}; } }
