using FluentValidation;
using Ssalddel.Application.Behaviors;
using Ssalddel.Application.CommandProcessing;
using Ssalddel.Application.Community;
using Ssalddel.Application.Community.Handlers;
using Ssalddel.Middleware;
using Ssalddel.Application.HumanResources;
using Ssalddel.Application.Sales;
using Ssalddel.Application.ViewSettings;
using Ssalddel.Application.Warehouse;
using Ssalddel.Application.WorldProjection;
using Ssalddel.Application.Customs;
using Ssalddel.Application.Audit;
using Ssalddel.Application.CommonContents;
using Ssalddel.Application.Images;
using Ssalddel.Application.Driver.Food;
using Ssalddel.Application.Food;
using Ssalddel.Application.Admin.Food;
using Ssalddel.Application.Admin.Restaurants;
using Ssalddel.Application.Mart;
using Ssalddel.Application.PublicData;
using Ssalddel.Application.Evidence;
using Ssalddel.Application.Files;
using Ssalddel.Application.Orderer;
using Ssalddel.Application.Settlement;
using Ssalddel.Application.Versioning;
using Ssalddel.Application.Security;
using Ssalddel.Application.ContractManagement;
using Ssalddel.Security;
using Ssalddel.Application.Operations;
using Ssalddel.Services.HumanResources;
using Ssalddel.Services.Community;
using Ssalddel.Services.Privacy;
using Ssalddel.Services.FoodCulture;
using Ssalddel.Services.Content;
using Ssalddel.Services.WorldProjection;
using Ssalddel.Services.LogisticsProcessing.SalesOrders;
using 살뜰.Infrastructure;
using 살뜰.Services.Audit;
using 살뜰.Services.Sales;
using 살뜰.Services.ViewSettings;
using Ssalddel.Services.LogisticsProcessing.Warehouse;
using Ssalddel.Services.LogisticsProcessing.VehicleLoading;
using Ssalddel.Services.Localization;
using Ssalddel.Application.Driver.Transport;
using 살뜰.Services.Transport;

namespace Ssalddel.Extensions;

public static partial class ServiceCollectionExtensions
{
    public static IServiceCollection AddSsalddelApplicationCore(this IServiceCollection services)
    {
        services.AddMediatR(cfg => cfg.RegisterServicesFromAssembly(typeof(Program).Assembly));
        services.AddValidatorsFromAssembly(typeof(Program).Assembly);
        services.AddTransient(typeof(IPipelineBehavior<,>), typeof(LoggingBehavior<,>));
        services.AddTransient(typeof(IPipelineBehavior<,>), typeof(ValidationBehavior<,>));
        services.AddTransient(typeof(IPipelineBehavior<,>), typeof(Command후처리Behavior<,>));
        services.AddTransient(typeof(IPipelineBehavior<,>), typeof(CommunityActivityCommandPostBehavior<,>));
        services.AddScoped(typeof(INotificationHandler<>), typeof(CommunityActivityEventPostEventHandler<>));

        services.AddSsalddelInfrastructure();
        services.AddScoped<ICurrentUserAccessor, HttpContextCurrentUserAccessor>();
        services.AddScoped<I개체시각대상Reader, 개체시각대상Reader>();
        services.AddSingleton<I개체시각자산Catalog, 개체시각자산Catalog>();
        services.AddScoped<개체시각대응UseCase>();
        services.AddScoped<개체시각목록UseCase>();
        services.AddScoped<게임객체시각구성UseCase>();
        services.AddScoped<게임객체WI참여UseCase>();
        services.AddScoped<보유시각자산목록UseCase>();
        services.AddScoped<I공급조직접근Accessor, 공급조직접근Accessor>();
        services.AddScoped<I플랫폼공급계약관리UseCase, 플랫폼공급계약관리UseCase>();
        services.AddScoped<I조직개별공급발주UseCase, 조직개별공급발주UseCase>();
        services.AddSingleton<IPublicLocaleRecommendationUseCase, PublicLocaleRecommendationUseCase>();
        services.AddScoped<I참여자실행권한검사, 참여자실행권한검사>();
        services.AddScoped<I사회보험신고UseCase, 사회보험신고UseCase>();
        services.AddScoped<IHR참여운영UseCase, HR참여운영UseCase>();
        services.AddScoped<IHR역할검토조회UseCase, HR역할검토조회UseCase>();
        services.AddScoped<IHR역할지원조회UseCase, HR역할지원조회UseCase>();
        services.AddScoped<IHR역할지원CommandUseCase, HR역할지원CommandUseCase>();
        services.AddScoped<I업무관계스냅샷조회UseCase, 업무관계스냅샷조회UseCase>();
        services.AddScoped<I기사운송상태변경CommandExecutor, 기사운송상태변경CommandExecutor>();
        services.AddScoped<ITransportRequestLedgerRealtimeService, TransportRequestLedgerRealtimeService>();
        services.AddScoped<I운송증빙첨부JsonWriter, 운송증빙첨부JsonWriter>();
        services.AddScoped<I운송완료입금요청Service, 운송완료입금요청Service>();
        services.AddScoped<ICommand기능설정Resolver, Command기능설정Resolver>();
        services.AddScoped<ICommand기능CatalogResolver, Command기능CatalogResolver>();
        services.AddScoped<IWorkRelationshipSnapshotCollector, WorkRelationshipSnapshotCollector>();
        services.AddScoped<ICommand후처리Processor, Command감사로그Processor>();
        services.AddScoped<ICommand후처리Processor, Command알림의도Processor>();
        services.AddScoped<ICommand후처리Processor, Command업무관계스냅샷Processor>();

        services.AddScoped<I사용자행위로그Service, 사용자행위로그Service>();
        services.AddScoped<SalesChannelService>();
        services.AddScoped<ISalesChannelService>(provider =>
            provider.GetRequiredService<SalesChannelService>());
        services.AddScoped<ISalesChannelCredentialProvider>(provider =>
            provider.GetRequiredService<SalesChannelService>());
        services.AddScoped<I판매채널UseCase, 판매채널UseCase>();
        services.AddScoped<I해외판매자식품시설UseCase, 해외판매자식품시설UseCase>();
        services.AddScoped<ISalesChannelOrderReadService, SalesChannelOrderReadService>();
        services.AddScoped<I판매채널주문조회UseCase, 판매채널주문조회UseCase>();
        services.AddScoped<I판매채널주문동기화UseCase, 판매채널주문동기화UseCase>();
        services.AddScoped<I판매페이지Service, 판매페이지Service>();
        services.AddScoped<I판매페이지UseCase, 판매페이지UseCase>();
        services.AddScoped<IView가시성Service, View가시성Service>();
        services.AddScoped<IView설정UseCase, View설정UseCase>();
        services.AddScoped<I관리자View정책UseCase, 관리자View정책UseCase>();
        services.AddScoped<I보조기능설정UseCase, 보조기능설정UseCase>();
        services.AddScoped<IHS코드운영UseCase, HS코드운영UseCase>();
        services.AddScoped<I화주HS코드검토조회UseCase, 화주HS코드검토조회UseCase>();
        services.AddScoped<I같이수입HS코드조회UseCase, 같이수입HS코드조회UseCase>();
        services.AddScoped<I사용자행위로그조회UseCase, 사용자행위로그조회UseCase>();
        services.AddScoped<I공통콘텐츠관리UseCase, 공통콘텐츠관리UseCase>();
        services.AddScoped<I샘플이미지작업UseCase, 샘플이미지작업UseCase>();
        services.AddScoped<I배달기사월정산UseCase, 배달기사월정산UseCase>();
        services.AddScoped<IFoodDeliveryDriverWorkspaceUseCase, FoodDeliveryDriverWorkspaceUseCase>();
        services.AddScoped<IFoodDeliveryDriverRouteService, FoodDeliveryDriverRouteService>();
        services.AddScoped<I음식주문접수UseCase, 음식주문접수UseCase>();
        services.AddScoped<I주문자음식주문조회UseCase, 주문자음식주문조회UseCase>();
        services.AddScoped<I음식주문운영추적UseCase, 음식주문운영추적UseCase>();
        services.AddScoped<I음식점음식주문조회UseCase, 음식점음식주문조회UseCase>();
        services.AddScoped<I음식점운영자접근관리UseCase, 음식점운영자접근관리UseCase>();
        services.AddScoped<I음식점탐색조회UseCase, 음식점탐색조회UseCase>();
        services.AddScoped<I음식점메뉴관리UseCase, 음식점메뉴관리UseCase>();
        services.AddScoped<I음식배달수명주기조회UseCase, 음식배달수명주기조회UseCase>();
        services.AddScoped<I음식점리뷰UseCase, 음식점리뷰UseCase>();
        services.AddScoped<I음식운영관리UseCase, 음식운영관리UseCase>();
        services.AddScoped<I마트공개상품조회UseCase, 마트공개상품조회UseCase>();
        services.AddScoped<I마트공개상품구매후기UseCase, 마트공개상품구매후기UseCase>();
        services.AddScoped<I마트주문요청조회UseCase, 마트주문요청조회UseCase>();
        services.AddScoped<I마트주문요청작성UseCase, 마트주문요청작성UseCase>();
        services.AddScoped<I마트피킹조회UseCase, 마트피킹조회UseCase>();
        services.AddSingleton<마트피킹포장WorldProjector>();
        services.AddScoped<I마트피킹포장World조회UseCase, 마트피킹포장World조회UseCase>();
        services.AddScoped<I공공데이터조회UseCase, 공공데이터조회UseCase>();
        services.AddSingleton<I공동구매상품CatalogUseCase, 공동구매상품CatalogUseCase>();
        services.AddScoped<I파일POD관리UseCase, 파일POD관리UseCase>();
        services.AddScoped<I문서관리UseCase, 문서관리UseCase>();
        services.AddScoped<I파일업로드UseCase, 파일업로드UseCase>();
        services.AddScoped<I공동구매해외선적추적UseCase, 공동구매해외선적추적UseCase>();
        services.AddScoped<I플랫폼수익환급UseCase, 플랫폼수익환급UseCase>();
        services.AddScoped<I버전워크플로우UseCase, 버전워크플로우UseCase>();
        services.AddScoped<IISMSP전송보호UseCase, ISMSP전송보호UseCase>();
        services.AddScoped<I커뮤니티게시판UseCase, 커뮤니티게시판UseCase>();
        services.AddScoped<ICommunityBoardWritePolicy, CommunityBoardWritePolicy>();
        services.AddScoped<커뮤니티게시글생성Service>();
        services.AddScoped<커뮤니티게시글UseCase>();
        services.AddScoped<I커뮤니티게시글UseCase>(provider =>
            provider.GetRequiredService<커뮤니티게시글UseCase>());
        services.AddScoped<I커뮤니티게시글조회UseCase, 커뮤니티게시글조회UseCase>();
        services.AddScoped<I커뮤니티게시글조회수기록UseCase, 커뮤니티게시글조회수기록UseCase>();
        services.AddScoped<I커뮤니티게시글발행UseCase, 커뮤니티게시글발행UseCase>();
        services.AddScoped<I커뮤니티게시글예약발행UseCase, 커뮤니티게시글예약발행UseCase>();
        services.AddScoped<I커뮤니티게시글첨부UseCase, 커뮤니티게시글첨부UseCase>();
        services.AddScoped<I커뮤니티게시글참여UseCase, 커뮤니티게시글참여UseCase>();
        services.AddScoped<I커뮤니티게시글운영UseCase, 커뮤니티게시글운영UseCase>();
        services.AddScoped<I커뮤니티투표UseCase, 커뮤니티투표UseCase>();
        services.AddScoped<I커뮤니티활동신호UseCase, 커뮤니티활동신호UseCase>();
        services.AddScoped<I커뮤니티시장광장조회UseCase, 커뮤니티시장광장조회UseCase>();
        services.AddScoped<I해외제조업소MapMarkerReader, 해외제조업소MapMarkerReader>();
        services.AddScoped<I지역문화이미지MapMarkerReader, 지역문화이미지MapMarkerReader>();
        services.AddScoped<I커뮤니티세계지도조회UseCase, 커뮤니티세계지도조회UseCase>();
        services.AddScoped<I커뮤니티세계지도뉴스후보UseCase, 커뮤니티세계지도뉴스후보UseCase>();
        services.AddScoped<I커뮤니티세계지도질문UseCase, 커뮤니티세계지도질문UseCase>();
        services.AddScoped<I노드스티커상점UseCase, 노드스티커상점UseCase>();
        services.AddScoped<I커뮤니티활동상세구매ProcessManager, 커뮤니티활동상세구매ProcessManager>();
        services.AddScoped<I커뮤니티활동유료상세UseCase, 커뮤니티활동유료상세UseCase>();
        services.AddScoped<ICommunityExperienceAwardService, CommunityExperienceAwardService>();
        services.AddScoped<ICommunityExperienceEventRecorder, CommunityExperienceEventRecorder>();
        services.AddScoped<IWarehouseOperationService, WarehouseOperationService>();
        services.AddScoped<IWarehousePerspectiveReadService, WarehousePerspectiveReadService>();
        services.AddScoped<ILoadingPerspectiveReadService, LoadingPerspectiveReadService>();
        services.AddScoped<IUnloadingPerspectiveReadService, UnloadingPerspectiveReadService>();
        services.AddScoped<IResidentialPickupPerspectiveUseCase, ResidentialPickupPerspectiveUseCase>();
        services.AddScoped<IFarmProducerPerspectiveUseCase, FarmProducerPerspectiveUseCase>();
        services.AddScoped<감자생산유통WorldProjector>();
        services.AddScoped<I감자생산유통World조회UseCase, 감자생산유통World조회UseCase>();
        services.AddScoped<IIndividualOrderPerspectiveReadService, IndividualOrderPerspectiveReadService>();
        services.AddScoped<IGroupOrderPerspectiveReadService, GroupOrderPerspectiveReadService>();
        services.AddScoped<I창고작업UseCase, 창고작업UseCase>();
        services.AddScoped<I창고작업진입UseCase, 창고작업진입UseCase>();
        services.AddScoped<I물류대행계약계획UseCase, 물류대행계약계획UseCase>();
        services.AddScoped<I피킹작업UseCase, 피킹작업UseCase>();
        services.AddScoped<I재고현황UseCase, 재고현황UseCase>();
        services.AddScoped<I창고WorldSnapshot조회UseCase, 창고WorldSnapshot조회UseCase>();
        services.AddScoped<I창고입고화물인계조회UseCase, 창고입고화물인계조회UseCase>();
        services.AddScoped<I적재작업UseCase, 적재작업UseCase>();
        services.AddScoped<I포장작업UseCase, 포장작업UseCase>();
        services.AddScoped<I출고인계준비UseCase, 출고인계준비UseCase>();
        services.AddScoped<I출고예정검토UseCase, 출고예정검토UseCase>();
        services.AddScoped<I출고운송인계완료UseCase, 출고운송인계완료UseCase>();
        services.AddScoped<IWarehouseServiceAreaPolicy, WarehouseServiceAreaPolicy>();
        services.AddScoped<IWarehouseDistanceCostEstimator, WarehouseDistanceCostEstimator>();
        services.AddScoped<IOutboundBatchEngine, OutboundBatchEngine>();
        services.AddScoped<I피킹배치Engine, 피킹배치Engine>();
        services.AddScoped<IWorkRelationshipSnapshotService, WorkRelationshipSnapshotService>();
        services.AddScoped<ICommunityActivitySignalService, CommunityActivitySignalService>();
        services.AddSingleton<ICommunityVoteStore, MongoCommunityVoteStore>();
        services.AddSingleton<I공식뉴스검토원장Store, Mongo공식뉴스검토원장Store>();
        services.AddScoped<I공식뉴스검토원장Service, 공식뉴스검토원장Service>();
        services.AddSingleton<ISynty공간조립검토원장Store, MongoSynty공간조립검토원장Store>();
        services.AddSingleton<ISynty공간조립검토촬영업로드Store, MongoSynty공간조립검토촬영업로드Store>();
        services.AddScoped<ISynty공간조립검토촬영업로드Service, Synty공간조립검토촬영업로드Service>();
        services.AddScoped<ISynty공간조립모바일검토Service, Synty공간조립모바일검토Service>();
        services.AddSingleton<I신청개인정보동의증적Store, Mongo신청개인정보동의증적Store>();
        services.AddScoped<I신청개인정보동의증적Service, 신청개인정보동의증적Service>();
        services.AddSingleton<I공동구매원장캠페인Store, CommunityVote공동구매원장캠페인Store>();
        services.AddScoped<I공동구매원장절차Service, 공동구매원장절차Service>();
        services.AddScoped<I같이수입원장전환Service, 같이수입원장전환Service>();
        services.AddScoped<ICommunityGroupPurchaseDemandOutboxProcessor, CommunityGroupPurchaseDemandOutboxProcessor>();
        services.AddScoped<ICommunityVoteService>(serviceProvider =>
            new CommunityVoteService(
                serviceProvider.GetRequiredService<ICommunityVoteStore>(),
                serviceProvider.GetRequiredService<ICommunityGroupPurchaseDemandOutboxProcessor>(),
                serviceProvider.GetRequiredService<I공동구매원장절차Service>(),
                serviceProvider.GetRequiredService<IOperatingMarketContextAccessor>()
                    .Current.Profile.CountryCode));
        services.AddScoped<ISalesChannelOrderSyncService, SalesChannelOrderSyncService>();
        services.AddSingleton<ISalesChannelOrderFeedClient, EmptySalesChannelOrderFeedClient>();
        services.AddScoped<IHrRoleAssignmentStore, EfCoreHrRoleAssignmentStore>();
        services.AddScoped<IHrEmploymentContractService, HrEmploymentContractService>();
        services.AddSingleton<IHrParticipationBenefitRecordService, InMemoryHrParticipationBenefitRecordService>();
        services.AddSingleton<ISocialInsuranceFilingService, InMemorySocialInsuranceFilingService>();
        services.AddScoped<HrRoleAccessMiddleware>();
        services.AddScoped<사용자행위로그Middleware>();

        return services;
    }
}
