<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>Ssalddel.Unity.Data</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Samples~\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ssalddel.BusinessWorkflow\Ssalddel.BusinessWorkflow.csproj" />
    <ProjectReference Include="..\Ssalddel.Interior.Contracts\Ssalddel.Interior.Contracts.csproj" />
    <ProjectReference Include="..\Ssalddel.CodeMetadata\Ssalddel.CodeMetadata.csproj" />
    <ProjectReference Include="..\Ssalddel.Simulation.Contracts\Ssalddel.Simulation.Contracts.csproj" />
    <ProjectReference Include="..\Ssalddel.WorkflowRules.Contracts\Ssalddel.WorkflowRules.Contracts.csproj" />
  </ItemGroup>

</Project>
