using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using Ssalddel.Client.Infrastructure;
using Ssalddel.Client.Infrastructure.Security;
using Ssalddel.Client.Infrastructure.Simulation;
using Ssalddel.Client.Infrastructure.Transport;
using Ssalddel.Contracts.Driver.Recommendation;
using Ssalddel.WebApp;
using Ssalddel.WebApp.Models;
using Ssalddel.WebApp.Services;
using Ssalddel.WebApp.ViewModels;
using Ssalddel.Ui.Common.Areas.App.Services;
using Ssalddel.Ui.Common.Areas.App.ViewModels;
using MudBlazor.Services;

var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.RootComponents.Add<App>("#app");
builder.RootComponents.Add<HeadOutlet>("head::after");

var apiBaseAddress = SsalddelApiEndpoint.ResolveBaseAddress(
    builder.Configuration[SsalddelApiEndpoint.ConfigurationKey],
    new Uri(builder.HostEnvironment.BaseAddress));
builder.Services.AddSsalddelApiHttpClient(apiBaseAddress);
builder.Services.AddRemoteBusinessWorkflowRuntime();
builder.Services.Configure<ClientDataModeOptions>(builder.Configuration.GetSection(ClientDataModeOptions.SectionName));
builder.Services.AddScoped<ITransportRequestLedgerObserver, TransportRequestLedgerObserver>();
builder.Services.AddSingleton<IPlatformCommunityNodeNavigationResolver, WebPlatformCommunityNodeNavigationResolver>();
builder.Services.AddSingleton<IPlatformHomeWorkspaceNavigationResolver, WebPlatformHomeWorkspaceNavigationResolver>();
builder.Services.AddSsalddelUiCommonAppServices<WebAuthSessionService>();
builder.Services.AddTransient<화주Controller기능모음ViewModel>();
builder.Services.AddSsalddelDocumentOutputServices();
builder.Services.AddSingleton<IClientSessionGuard, ClientSessionGuard>();
builder.Services.AddScoped<WebAuthSessionService>();
builder.Services.AddScoped<I주문자앱인증Service, WebOrdererAuthenticationService>();
builder.Services.AddScoped<CommunityPersonalPreferenceService>();
builder.Services.AddScoped<커뮤니티세계지도Client>();
builder.Services.AddScoped<지역문화이미지Client>();
builder.Services.AddScoped<GoogleMapsBrowserRuntimeClient>();
builder.Services.AddScoped<OrdererBetaReadinessService>();
builder.Services.AddScoped<PreviewBuildManifestService>();
builder.Services.AddTransient<CommunityPersonalPageViewModel>();
builder.Services.AddScoped<WebLocalePreferenceService>();
builder.Services.AddScoped<ApplicationPrivacyConsentClient>();
builder.Services.AddScoped<CommunityMapApplicationLedgerClient>();
builder.Services.AddScoped<MapApplicationOperationalCancellationClient>();
builder.Services.AddScoped<IDiagramCollaborationClientService, DiagramCollaborationClientService>();
builder.Services.AddScoped<WebShipperWarehouseWorkspaceService>();
builder.Services.AddScoped<IWarehouseWorkspaceService>(sp => sp.GetRequiredService<WebShipperWarehouseWorkspaceService>());
builder.Services.AddTransient<InboundRequestPageViewModel>();
builder.Services.AddTransient<ShipperSalesProductsPageViewModel>();
builder.Services.AddTransient<ShipperSalesProductCreatePageViewModel>();
builder.Services.AddTransient<ShipperSalesListingsPageViewModel>();
builder.Services.AddTransient<ShipperSalesListingCreatePageViewModel>();
builder.Services.AddScoped<GlobalTradeWorkspaceService>();
builder.Services.AddScoped<IWarehouseWorkEntryGateService, SampleWarehouseWorkEntryGateService>();
builder.Services.AddScoped<운송의뢰자동저장Service>();
builder.Services.AddScoped<커뮤니티화물글초안가져오기Service>();
builder.Services.AddScoped<화주운송의뢰등록Service>();
builder.Services.AddScoped<ShipperRequestAuthoringPageViewModel>();
builder.Services.AddScoped<ShipperRequestDetailPageViewModel>();
builder.Services.AddScoped<화주결제정산Service>();
builder.Services.AddScoped<기사내정보Service>();
builder.Services.AddScoped<기사정산Service>();
builder.Services.AddScoped<기사알림Service>();
builder.Services.AddScoped<기사운행Service>();
builder.Services.AddScoped<기사추천수신Service>();
builder.Services.AddScoped<I기사추천수신Service>(sp => sp.GetRequiredService<기사추천수신Service>());
builder.Services.AddScoped<기사운송증빙Service>();
builder.Services.AddTransient<DriverRecommendationDecisionPageViewModel>();
builder.Services.AddTransient<DriverCurrentTransportPageViewModel>();
builder.Services.AddTransient<DriverTransportPickupPageViewModel>();
builder.Services.AddTransient<DriverTransportDropoffPageViewModel>();
builder.Services.AddScoped<운송의뢰작성ViewModel>();
builder.Services.AddMudServices();

await builder.Build().RunAsync();
